name = "wing-personal-assistant"
main = "src/index.ts"
compatibility_date = "2026-08-11"

[observability]
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "STATE"
id = "c1670557042b4c79bfe975fe00d78fc7"
